### PR TITLE
Use parent _segments array instead of deriving from subviews which wa…

### PR DESCRIPTION
**Pull request by reganApe**
…s buggy

### CODE REVIEW

**Comment by yonat** [comment]
Thanks! I'll check this out as soon as have some time.

**Comment by StainlessStlRat** [comment]
Is this going to be merged?

**Comment by yonat** [comment]
Initial testing didn't reveal any difference in behavior. Does it fix a problem you encountered?

**Comment by yonat** [comment]
Not applicable in 2.0.0.

**Pull request closed without merging**
